### ISSUE TITLE
100% height

### ISSUE THREAD

**Issue by MarceloBritoWD** [JamyGolden/PlusSlider#24]
Hey man, can i put 100% height in this slider?

**Comment by RichardLindhout** [comment]
You can put the image in a background of a div.

background: url(images/bg.jpg) no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;


also css
height:100vh; makes it 100% height but not in all browsers.
