### ISSUE TITLE
Weird bug can't click next

### ISSUE THREAD

**Issue by RichardLindhout** [JamyGolden/PlusSlider#25]
I am currently redesigning a client's website and updated the plusslider to the newer version. It's a nice plugin but I have to click to all items first (dots do change). For example http://floradetuinen.nl/portfolio/moderne-tuin/ I don't know how to fix. Can you help me out? Would be cool :+1:

**Comment by JamyGolden** [comment]
Hi Richard. Remove this from your style.css file - Line 439:
```#slider li {
	display: block;
}```

That should fix the problem.

**Comment by RichardLindhout** [comment]
Thanks!! Was indeed display:block; Thanks for helping me out. I didn't know I had the lines of the older plusslider plugin left.
